import spotipy
from spotipy.oauth2 import SpotifyOAuth
import os

# --- ENTER YOUR DASHBOARD DETAILS HERE ---
# Make sure these match the App where you just added your email!
CLIENT_ID = "2ee56b2a6844469cb31728502233761e"
CLIENT_SECRET = "da75badeb99a4411959bec12db8c2a57"
REDIRECT_URI = "http://127.0.0.1:8080/" # Must match your Spotify Dashboard

def validate_and_generate():
    print("--- 1. STARTING AUTHENTICATION ---")
    
    # We explicitly request write permissions
    scope = "playlist-modify-public playlist-modify-private user-read-email"
    
    sp_oauth = SpotifyOAuth(
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
        redirect_uri=REDIRECT_URI,
        scope=scope,
        show_dialog=True,  # Forces the "Agree" screen
        cache_handler=None # Disables cache to force fresh token
    )
    
    # Generate Auth Link
    auth_url = sp_oauth.get_authorize_url()
    print(f"\n[ACTION] Open this URL in your browser:\n{auth_url}\n")
    print("1. Click 'Agree' (Ensure 'Manage your playlists' is checked).")
    print("2. Copy the full URL you are redirected to.")
    
    redirected_url = input("\nPaste the redirect URL here: ").strip()
    
    try:
        # Get Token
        code = sp_oauth.parse_response_code(redirected_url)
        token_info = sp_oauth.get_access_token(code)
        access_token = token_info['access_token']
        refresh_token = token_info['refresh_token']
        
        # Verify Scopes
        if "playlist-modify" not in token_info['scope']:
            print("\n[ERROR] Token missing permissions. You may have unchecked the boxes.")
            return

        print("\n--- 2. VERIFYING WRITE ACCESS ---")
        sp = spotipy.Spotify(auth=access_token)
        user_id = sp.current_user()['id']
        print(f"Logged in as: {user_id}")
        
        # Test: Create a playlist
        playlist = sp.user_playlist_create(
            user=user_id, 
            name="Daily News (Automated)", 
            public=True, 
            description="Generated by Python Validator"
        )
        print(f"[SUCCESS] Created Playlist ID: {playlist['id']}")
        
        # Test: Add a track (The ultimate test)
        sp.playlist_add_items(playlist['id'], ["spotify:track:4cOdK2wGLETKBW3PvgPWqT"])
        print(f"[SUCCESS] Added track to playlist.")
        
        print("\n" + "="*50)
        print("   ✅ COPY THESE VALUES TO GITHUB SECRETS ✅")
        print("="*50)
        print(f"SPOTIPY_CLIENT_ID:     {CLIENT_ID}")
        print(f"SPOTIPY_CLIENT_SECRET: {CLIENT_SECRET}")
        print(f"SPOTIPY_REFRESH_TOKEN: {refresh_token}")
        print(f"TARGET_PLAYLIST_ID:    {playlist['id']}")
        print("="*50)
        print("\nIf you copy these exactly, the GitHub Action WILL work.")

    except Exception as e:
        print(f"\n[FAILURE] Error: {e}")
        if "403" in str(e):
            print("\n!!! DIAGNOSIS: 403 FORBIDDEN !!!")
            print("1. Your email is NOT listed in the Spotify Dashboard 'User Management'.")
            print("2. Or you are logging in with a different email than the one you added.")

if __name__ == "__main__":
    validate_and_generate()